// @ts-nocheck
"use client";

import { Box, ChevronRight, CircleDot, Crosshair, Download, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type AssetFeature = { id?: string; geometry?: { type?: string; coordinates?: unknown }; properties: Record<string, unknown> };
type AssetCollection = { type: string; features: AssetFeature[] };
type TabKey = "PK" | "SECCION" | "IFC" | "HISTORIAL" | "DECISION" | "COMPARAR" | "OT";
type WorkOrder = { id:string; assetId:string; codigo:string; tipo:string; tarea:string; responsable:string; vencimiento:string; prioridad:string; estado:string; creado:string };

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "https://wjbuukqqxypclvwwclxe.supabase.co";
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? "sb_publishable_QhSYofToTULcOQ5pynkCoQ_Ha6Om1w9";
const WORK_ORDER_KEY = "rn174_work_orders_v1";
const n = (value: unknown) => { const out = Number(value); return Number.isFinite(out) ? out : undefined; };
const s = (value: unknown) => String(value ?? "").trim();

function parsePk(value: string) {
  const text = value.toUpperCase().replace("PK", "").replace(/\s/g, "").replace(",", ".");
  if (!text) return undefined;
  if (text.includes("+")) { const [km,m] = text.split("+").map(Number); if (Number.isFinite(km) && Number.isFinite(m)) return km*1000+m; }
  const direct = Number(text); return Number.isFinite(direct) ? direct : undefined;
}
function formatPk(value?: number) { if (value === undefined || !Number.isFinite(value)) return "—"; const km=Math.floor(value/1000); return `PK ${km}+${(value-km*1000).toFixed(2).padStart(6,"0")}`; }
function assetPk(feature?: AssetFeature) { if (!feature) return undefined; return n(feature.properties.progresiva_inicio_m) ?? n(feature.properties.progresiva_m); }
function featureKey(feature: AssetFeature) { return s(feature.properties.codigo) || s(feature.id); }
function distanceToPk(feature: AssetFeature, pk:number) { const start=n(feature.properties.progresiva_inicio_m) ?? n(feature.properties.progresiva_m); const end=n(feature.properties.progresiva_fin_m) ?? start; if(start===undefined)return Infinity; if(end!==undefined && pk>=Math.min(start,end) && pk<=Math.max(start,end))return 0; return Math.min(Math.abs(pk-start), end===undefined?Infinity:Math.abs(pk-end)); }
function setReactInputValue(input:HTMLInputElement,value:string){const setter=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,"value")?.set;if(setter)setter.call(input,value);else input.value=value;input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));}
function openAssetInGis(feature?:AssetFeature){if(!feature)return;const input=document.querySelector<HTMLInputElement>(".global-search-wrap input");if(!input)return;const term=s(feature.properties.codigo)||s(feature.id);if(!term)return;input.focus();setReactInputValue(input,term);let tries=0;const pick=()=>{const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>(".global-search-results button"));if(buttons[0]){buttons[0].click();return;}tries++;if(tries<10)window.setTimeout(pick,120);};window.setTimeout(pick,120);}
function downloadText(text:string,filename:string,type="text/plain;charset=utf-8"){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}

function SectionT13({pk}:{pk:number}){
  const crownHalf=11.95,height=3,toe=crownHalf+height*4; const x=(m:number)=>300+m*9.2, y=(m:number)=>72+m*25;
  return <div className="v4-section-box"><div className="v4-section-title"><strong>Sección tipo T13 · referencia documental</strong><span>{formatPk(pk)}</span></div><svg viewBox="0 0 600 205" role="img" aria-label="Sección transversal T13"><line x1="40" y1="148" x2="560" y2="148" className="v4-ground"/><polygon points={`${x(-toe)},${y(height)} ${x(-crownHalf)},${y(0)} ${x(crownHalf)},${y(0)} ${x(toe)},${y(height)}`} className="v4-fill"/><rect x={x(-crownHalf)} y="59" width={crownHalf*2*9.2} height="13" className="v4-layer l1"/><rect x={x(-crownHalf)} y="52" width={crownHalf*2*9.2} height="7" className="v4-layer l2"/><rect x={x(-crownHalf)} y="47" width={crownHalf*2*9.2} height="5" className="v4-layer l3"/><line x1={x(0)} y1="39" x2={x(0)} y2="148" className="v4-axis"/><text x="300" y="34" textAnchor="middle">EJE</text><text x="300" y="92" textAnchor="middle">coronamiento 23,90 m</text><text x="107" y="128" textAnchor="middle">talud 1V:4H</text><text x="493" y="128" textAnchor="middle">talud 1V:4H</text><text x="300" y="176" textAnchor="middle">esquema paramétrico · no reemplaza sección levantada</text></svg></div>;
}
function InventoryStrip({features,pk}:{features:AssetFeature[];pk:number}){
  const nearby=features.filter(f=>{const p=assetPk(f);return p!==undefined&&Math.abs(p-pk)<=500;}); const families=Array.from(new Set(nearby.map(f=>s(f.properties.familia)||"OTROS"))).slice(0,5); const min=pk-500; const xpos=(v:number)=>90+((v-min)/1000)*470;
  return <div className="v4-section-box"><div className="v4-section-title"><strong>Perfil longitudinal de inventario</strong><span>±500 m · {nearby.length} activos</span></div><svg viewBox="0 0 600 190"><line x1="90" y1="25" x2="560" y2="25" className="v4-ground"/><line x1={xpos(pk)} y1="12" x2={xpos(pk)} y2="174" className="v4-axis"/><text x="90" y="16">{formatPk(min).replace("PK ","")}</text><text x="560" y="16" textAnchor="end">{formatPk(pk+500).replace("PK ","")}</text>{families.map((family,row)=><g key={family}><text x="8" y={54+row*25}>{family.slice(0,12)}</text><line x1="90" y1={50+row*25} x2="560" y2={50+row*25} className="v4-rowline"/>{nearby.filter(f=>(s(f.properties.familia)||"OTROS")===family).slice(0,80).map((f,i)=><circle key={`${featureKey(f)}-${i}`} cx={xpos(assetPk(f)!)} cy={50+row*25} r="3.2" className="v4-dot"/>)}</g>)}</svg></div>;
}

export function VisorV4Tools(){
  const [open,setOpen]=useState(false),[tab,setTab]=useState<TabKey>("PK");
  const [collection,setCollection]=useState<AssetCollection|null>(null),[loadError,setLoadError]=useState("");
  const [selectedId,setSelectedId]=useState(""),[pkText,setPkText]=useState("5+200"),[pk,setPk]=useState<number|undefined>(5200);
  const [ifcModel,setIfcModel]=useState(""),[ifcProps,setIfcProps]=useState<Array<[string,string]>>([]);
  const [decision,setDecision]=useState({seguridad:0,condicion:0,legal:0,transito:0,costo:""});
  const [lotA,setLotA]=useState(""),[lotB,setLotB]=useState("");
  const [orders,setOrders]=useState<WorkOrder[]>([]),[taskType,setTaskType]=useState("INSPECCION"),[taskText,setTaskText]=useState(""),[responsible,setResponsible]=useState(""),[due,setDue]=useState(""),[priority,setPriority]=useState("MEDIA");

  useEffect(()=>{let cancelled=false;async function load(){try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/rn174_activos_v32_geojson`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({p_tipo_codigo:null,p_progresiva_desde_m:null,p_progresiva_hasta_m:null})});if(!response.ok)throw new Error(`HTTP ${response.status}`);const json=await response.json() as AssetCollection;if(!cancelled)setCollection(json);}catch(error){if(!cancelled)setLoadError(error instanceof Error?error.message:"No se pudo leer inventario");}}void load();try{const raw=localStorage.getItem(WORK_ORDER_KEY);if(raw)setOrders(JSON.parse(raw));}catch{}return()=>{cancelled=true;};},[]);
  useEffect(()=>{const readDom=()=>{const id=document.querySelector<HTMLElement>(".dock-identity strong")?.textContent?.trim()??"";if(id)setSelectedId(id);const activeButton=Array.from(document.querySelectorAll<HTMLButtonElement>(".bim-model-picker button.active"))[0];setIfcModel(activeButton?.textContent?.trim()??document.querySelector<HTMLElement>(".bim-panel .panel-titlebar span")?.textContent?.trim()??"");const pairs=Array.from(document.querySelectorAll<HTMLElement>(".bim-semantic-inspector p")).map(row=>[row.querySelector("span")?.textContent?.trim()??"",row.querySelector("b")?.textContent?.trim()??""] as [string,string]).filter(([key])=>key);setIfcProps(pairs);};readDom();const timer=window.setInterval(readDom,450);return()=>window.clearInterval(timer);},[]);

  const features=collection?.features??[]; const selected=useMemo(()=>features.find(f=>s(f.id)===selectedId||s(f.properties.codigo)===selectedId),[features,selectedId]); const parsedPk=pk??assetPk(selected);
  const nearest=useMemo(()=>parsedPk===undefined?[]:[...features].map(feature=>({feature,distance:distanceToPk(feature,parsedPk)})).filter(i=>Number.isFinite(i.distance)).sort((a,b)=>a.distance-b.distance).slice(0,12),[features,parsedPk]);
  const lots=useMemo(()=>Array.from(new Set(features.map(f=>s(f.properties.lote_origen)).filter(Boolean))).sort(),[features]);
  useEffect(()=>{if(!lotA&&lots[0])setLotA(lots[0]);if(!lotB&&lots[1])setLotB(lots[1]);},[lots,lotA,lotB]);
  const comparison=useMemo(()=>{if(!lotA||!lotB||lotA===lotB)return null;const a=features.filter(f=>s(f.properties.lote_origen)===lotA),b=features.filter(f=>s(f.properties.lote_origen)===lotB);const ma=new Map(a.map(f=>[featureKey(f),f])),mb=new Map(b.map(f=>[featureKey(f),f]));const added=[...mb.keys()].filter(k=>!ma.has(k)),removed=[...ma.keys()].filter(k=>!mb.has(k)),common=[...ma.keys()].filter(k=>mb.has(k));const moved=common.filter(k=>{const pa=assetPk(ma.get(k)),pb=assetPk(mb.get(k));return pa!==undefined&&pb!==undefined&&Math.abs(pa-pb)>1;});return{a:a.length,b:b.length,added,removed,common,moved};},[features,lotA,lotB]);
  const completeness=useMemo(()=>{if(!selected)return 0;const p=selected.properties;const values=[p.codigo,p.familia,p.tipo_activo??p.tipo,p.progresiva_inicio_m??p.progresiva_m,p.estado_validacion,p.calidad_dato,p.precision_m,p.lote_origen];return Math.round(values.filter(v=>v!==undefined&&v!==null&&v!=="").length/values.length*100);},[selected]);
  const score=Math.round(((decision.seguridad*.35+decision.condicion*.25+decision.legal*.2+decision.transito*.2)/5)*100); const scoreLabel=score>=75?"MUY ALTA":score>=55?"ALTA":score>=35?"MEDIA":score>0?"BAJA":"SIN EVALUAR";
  const locatePk=()=>{const value=parsePk(pkText);setPk(value);if(value===undefined||!features.length)return;const match=[...features].map(feature=>({feature,distance:distanceToPk(feature,value)})).sort((a,b)=>a.distance-b.distance)[0];if(match?.feature)openAssetInGis(match.feature);};
  const saveDecision=()=>{if(selectedId)localStorage.setItem(`rn174_decision_${selectedId}`,JSON.stringify({...decision,score,savedAt:new Date().toISOString()}));};
  useEffect(()=>{if(!selectedId)return;try{const raw=localStorage.getItem(`rn174_decision_${selectedId}`);if(raw){const saved=JSON.parse(raw);setDecision({seguridad:Number(saved.seguridad)||0,condicion:Number(saved.condicion)||0,legal:Number(saved.legal)||0,transito:Number(saved.transito)||0,costo:String(saved.costo??"")});}else setDecision({seguridad:0,condicion:0,legal:0,transito:0,costo:""});}catch{}},[selectedId]);
  const createOrder=()=>{if(!selected||!taskText.trim())return;const p=selected.properties;const item:WorkOrder={id:`OT-${Date.now()}`,assetId:s(selected.id),codigo:s(p.codigo),tipo:taskType,tarea:taskText.trim(),responsable:responsible.trim(),vencimiento:due,prioridad:priority,estado:"ABIERTA",creado:new Date().toISOString()};const next=[item,...orders];setOrders(next);localStorage.setItem(WORK_ORDER_KEY,JSON.stringify(next));setTaskText("");};
  const exportOrders=()=>{const header=["id","asset_id","codigo","tipo","tarea","responsable","vencimiento","prioridad","estado","creado"];const rows=orders.map(o=>header.map(key=>`"${String(o[key as keyof WorkOrder]??"").replace(/"/g,'""')}"`).join(","));downloadText([header.join(","),...rows].join("\n"),"RN174_ordenes_trabajo_local.csv","text/csv;charset=utf-8");};
  const tabs:Array<[TabKey,string]>=[["PK","PK"],["SECCION","Sección"],["IFC","IFC"],["HISTORIAL","Historial"],["DECISION","Decisión"],["COMPARAR","Comparar"],["OT","OT / Inspección"]];

  return <><button className="v4-launch" type="button" onClick={()=>setOpen(true)}><Box size={15}/> Ingeniería</button>{open&&<aside className="v4-console"><header className="v4-head"><div><Box size={17}/><span><strong>Consola de Ingeniería</strong><small>RN174 · análisis no invasivo</small></span></div><button onClick={()=>setOpen(false)}><X size={16}/></button></header><div className="v4-tabs">{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</div><div className="v4-body">{loadError&&<div className="v4-alert">No se pudo cargar la capa analítica: {loadError}</div>}
  {tab==="PK"&&<><section className="v4-card"><h3>Consulta por progresiva</h3><div className="v4-inline"><input value={pkText} onChange={e=>setPkText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&locatePk()} placeholder="Ej. 5+200"/><button onClick={locatePk}><Crosshair size={14}/> Localizar</button></div><p>Acepta <b>5+200</b>, <b>PK 5+200</b> o metros absolutos.</p></section><section className="v4-card"><h3>Activos más próximos · {parsedPk!==undefined?formatPk(parsedPk):"sin PK"}</h3>{nearest.length?<div className="v4-list">{nearest.map(({feature,distance})=><button key={`${featureKey(feature)}-${distance}`} onClick={()=>openAssetInGis(feature)}><span><b>{s(feature.properties.codigo)||s(feature.id)}</b><small>{s(feature.properties.nombre)||s(feature.properties.tipo_activo)||s(feature.properties.tipo)}</small></span><em>{distance<.5?"en PK":`${distance.toFixed(1)} m`}</em><ChevronRight size={14}/></button>)}</div>:<p>Sin resultados.</p>}</section></>}
  {tab==="SECCION"&&<>{parsedPk!==undefined&&parsedPk>=4632.6&&parsedPk<=4800?<SectionT13 pk={parsedPk}/>:<div className="v4-note"><strong>Sección transversal</strong><span>No existe una sección paramétrica validada para este PK. Para evitar inventar geometría, sólo se dibuja T13 dentro de PK 4+632,60–4+800,00.</span></div>}{parsedPk!==undefined&&<InventoryStrip features={features} pk={parsedPk}/>}</>}
  {tab==="IFC"&&<><section className="v4-card"><h3>Modelo IFC activo</h3><p className="v4-strong">{ifcModel||"Ningún modelo identificado"}</p><p>Seleccioná un componente en el visor 3D. Si el modelo posee semántica RN174, sus propiedades aparecen aquí sin modificar el visor.</p></section>{ifcProps.length?<section className="v4-card"><h3>Propiedades del componente</h3><div className="v4-props">{ifcProps.map(([key,value])=><p key={key}><span>{key}</span><b>{value}</b></p>)}</div></section>:<div className="v4-note"><strong>Sin componente seleccionado</strong><span>Puente San Martín y T13 ya exponen propiedades por componente. Los modelos visuales anteriores seguirán funcionando sin cambios.</span></div>}</>}
  {tab==="HISTORIAL"&&<section className="v4-card"><h3>Historial disponible del activo</h3>{selected?<div className="v4-timeline"><div><i/><span><b>Estado 0 / origen</b><small>{s(selected.properties.lote_origen)||"fuente no indicada"}</small></span></div>{Boolean(selected.properties.actualizado_en)&&<div><i/><span><b>Última actualización GIS</b><small>{s(selected.properties.actualizado_en)}</small></span></div>}<div><i/><span><b>Validación actual</b><small>{s(selected.properties.estado_validacion)||"SIN ESTADO"}</small></span></div><div className="muted"><i/><span><b>Inspecciones / intervenciones</b><small>No existen eventos históricos estructurados en el dataset público actual.</small></span></div></div>:<p>Seleccioná un activo en el GIS.</p>}</section>}
  {tab==="DECISION"&&<><section className="v4-card"><h3>Escenario de priorización</h3><p>Evaluación manual transparente. No asigno riesgo automáticamente con datos incompletos.</p>{([['seguridad','Seguridad'],['condicion','Condición física'],['legal','Riesgo legal'],['transito','Impacto operativo']] as const).map(([key,label])=><label className="v4-slider" key={key}><span>{label}<b>{decision[key]}/5</b></span><input type="range" min="0" max="5" step="1" value={decision[key]} onChange={e=>setDecision(d=>({...d,[key]:Number(e.target.value)}))}/></label>)}<label className="v4-field"><span>Costo estimado opcional</span><input value={decision.costo} onChange={e=>setDecision(d=>({...d,costo:e.target.value}))} placeholder="$ / unidad monetaria"/></label></section><section className="v4-score"><span>Prioridad de escenario</span><strong>{score}</strong><b>{scoreLabel}</b><small>35% seguridad · 25% condición · 20% legal · 20% operación</small><button onClick={saveDecision} disabled={!selectedId}>Guardar local para este activo</button></section><div className="v4-note"><strong>Completitud del activo: {completeness}%</strong><span>El puntaje de escenario es una ayuda comparativa, no una decisión contractual ni una inspección.</span></div></>}
  {tab==="COMPARAR"&&<><section className="v4-card"><h3>Comparador por lote / campaña</h3><label className="v4-field"><span>Lote A</span><select value={lotA} onChange={e=>setLotA(e.target.value)}>{lots.map(lot=><option key={lot}>{lot}</option>)}</select></label><label className="v4-field"><span>Lote B</span><select value={lotB} onChange={e=>setLotB(e.target.value)}>{lots.map(lot=><option key={lot}>{lot}</option>)}</select></label></section>{comparison?<section className="v4-card"><div className="v4-metrics"><div><span>A</span><b>{comparison.a}</b></div><div><span>B</span><b>{comparison.b}</b></div><div><span>Nuevos</span><b>{comparison.added.length}</b></div><div><span>Ausentes</span><b>{comparison.removed.length}</b></div><div><span>Comunes</span><b>{comparison.common.length}</b></div><div><span>PK cambiado</span><b>{comparison.moved.length}</b></div></div><p>Comparación por código/ID dentro de cada lote. Sirve para detección preliminar; no reemplaza conciliación de campañas.</p></section>:<div className="v4-note"><strong>Elegí dos lotes distintos</strong><span>La comparación se calcula íntegramente en el navegador.</span></div>}</>}
  {tab==="OT"&&<><section className="v4-card"><h3>Nueva orden / inspección</h3><p className="v4-strong">{selected?`${s(selected.properties.codigo)||s(selected.id)} · ${s(selected.properties.nombre)||s(selected.properties.tipo_activo)||"Activo"}`:"Seleccioná un activo GIS"}</p><div className="v4-grid2"><label className="v4-field"><span>Tipo</span><select value={taskType} onChange={e=>setTaskType(e.target.value)}><option>INSPECCION</option><option>VERIFICACION</option><option>CONSERVACION</option><option>REPARACION</option></select></label><label className="v4-field"><span>Prioridad</span><select value={priority} onChange={e=>setPriority(e.target.value)}><option>BAJA</option><option>MEDIA</option><option>ALTA</option><option>URGENTE</option></select></label></div><label className="v4-field"><span>Tarea</span><textarea value={taskText} onChange={e=>setTaskText(e.target.value)} placeholder="Qué debe verificarse o ejecutarse"/></label><div className="v4-grid2"><label className="v4-field"><span>Responsable</span><input value={responsible} onChange={e=>setResponsible(e.target.value)}/></label><label className="v4-field"><span>Vencimiento</span><input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div><button className="v4-primary" onClick={createOrder} disabled={!selected||!taskText.trim()}>Crear local</button></section><section className="v4-card"><div className="v4-title-row"><h3>Órdenes locales · {orders.length}</h3><button onClick={exportOrders} disabled={!orders.length}><Download size={13}/> CSV</button></div><div className="v4-orders">{orders.slice(0,8).map(order=><div key={order.id}><span><b>{order.tipo} · {order.prioridad}</b><small>{order.codigo} · {order.tarea}</small></span><em>{order.estado}</em></div>)}</div><p>Persisten sólo en este navegador. No escriben en Supabase hasta definir permisos, auditoría y workflow.</p></section></>}
  </div><footer><CircleDot size={11}/> V4 experimental en capa independiente · no modifica GIS/IFC/CDE</footer></aside>}
  <style>{`
  .v4-launch{position:fixed;left:128px;bottom:104px;z-index:2400;display:flex;align-items:center;gap:6px;padding:8px 11px;border:1px solid #0b7acb;border-radius:6px;background:#0b7acb;color:#fff;font-size:10.5px;font-weight:850;box-shadow:0 6px 20px #0f172a33;cursor:pointer}.v4-launch:hover{background:#075f9e}
  .v4-console{position:fixed;left:12px;top:78px;bottom:100px;z-index:2600;width:min(465px,calc(100vw - 24px));display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;background:#f7f9fc;border:1px solid #b9c8d8;border-radius:9px;box-shadow:0 20px 55px #0f172a44;overflow:hidden;color:#24364d;font-family:Arial,Helvetica,sans-serif}.v4-head{height:54px;display:flex;align-items:center;justify-content:space-between;padding:0 13px;background:#0d1c34;color:#fff}.v4-head>div{display:flex;align-items:center;gap:8px}.v4-head span{display:grid}.v4-head strong{font-size:12.5px}.v4-head small{font-size:9px;color:#93b4d7}.v4-head button{display:grid;place-items:center;width:28px;height:28px;border:1px solid #ffffff33;border-radius:5px;background:#ffffff0d;color:#fff;cursor:pointer}
  .v4-tabs{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;padding:7px;background:#e8eef5}.v4-tabs button{min-height:29px;padding:5px 4px;border:1px solid #cbd6e2;border-radius:4px;background:#fff;color:#4c6077;font-size:9.5px;font-weight:800;cursor:pointer}.v4-tabs button.active{background:#0b7acb;border-color:#0b7acb;color:#fff}.v4-body{overflow:auto;padding:10px}
  .v4-card,.v4-section-box,.v4-note,.v4-score{margin-bottom:9px;padding:10px;background:#fff;border:1px solid #d8e1eb;border-radius:6px}.v4-card h3{margin:0 0 8px;font-size:11.5px;color:#14263e}.v4-card p,.v4-note span{margin:5px 0;color:#62748a;font-size:9.5px;line-height:1.38}.v4-strong{color:#163e66!important;font-weight:800}.v4-alert{margin-bottom:8px;padding:8px;background:#fff1f2;border:1px solid #fecdd3;border-radius:5px;color:#991b1b;font-size:9.5px}
  .v4-inline{display:grid;grid-template-columns:1fr auto;gap:6px}.v4-inline input,.v4-field input,.v4-field select,.v4-field textarea{width:100%;box-sizing:border-box;border:1px solid #c9d4df;border-radius:4px;background:#fff;color:#26384e;font-size:10px}.v4-inline input,.v4-field input,.v4-field select{height:31px;padding:0 8px}.v4-field textarea{min-height:62px;padding:7px;resize:vertical}.v4-inline button,.v4-primary,.v4-title-row button,.v4-score button{display:flex;align-items:center;justify-content:center;gap:5px;padding:7px 9px;border:1px solid #0b7acb;border-radius:4px;background:#0b7acb;color:#fff;font-size:9.5px;font-weight:800;cursor:pointer}.v4-inline button:disabled,.v4-primary:disabled,.v4-title-row button:disabled,.v4-score button:disabled{opacity:.45;cursor:not-allowed}
  .v4-list{display:grid;gap:4px}.v4-list button{display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:center;gap:7px;padding:7px;border:1px solid #e0e7ef;border-radius:4px;background:#fbfdff;text-align:left;cursor:pointer}.v4-list button:hover{border-color:#7db7e1;background:#eff8ff}.v4-list span{display:grid;min-width:0}.v4-list b{overflow:hidden;color:#0b6fae;font-size:9.5px;text-overflow:ellipsis;white-space:nowrap}.v4-list small{overflow:hidden;color:#64748b;font-size:8.5px;text-overflow:ellipsis;white-space:nowrap}.v4-list em{font-size:8.5px;color:#475569;font-style:normal}
  .v4-section-title{display:flex;justify-content:space-between;gap:8px;margin-bottom:5px;font-size:10px}.v4-section-title span{color:#64748b}.v4-section-box svg{display:block;width:100%;height:auto;background:#f8fbfe;border:1px solid #edf2f7;border-radius:4px}.v4-section-box svg text{font-size:10px;fill:#52657b}.v4-ground{stroke:#7d8c9c;stroke-width:1}.v4-fill{fill:#b89572;stroke:#8b684c;stroke-width:1}.v4-layer{stroke:#3e4c5e;stroke-width:.5}.v4-layer.l1{fill:#c5b58f}.v4-layer.l2{fill:#5f6874}.v4-layer.l3{fill:#2e3743}.v4-axis{stroke:#e11d48;stroke-width:1.2;stroke-dasharray:4 3}.v4-rowline{stroke:#d7e0e8;stroke-width:1}.v4-dot{fill:#0b7acb}
  .v4-note{display:grid;gap:4px;background:#f8fbff;border-left:4px solid #0b7acb}.v4-note strong{font-size:10.5px}.v4-props p{display:grid;grid-template-columns:42% 58%;margin:0;border-top:1px solid #edf1f5}.v4-props p:first-child{border-top:0}.v4-props span,.v4-props b{padding:5px 4px;font-size:9px;word-break:break-word}.v4-props span{color:#64748b}.v4-props b{color:#24364d}.v4-timeline{display:grid}.v4-timeline>div{position:relative;display:grid;grid-template-columns:18px 1fr;gap:6px;min-height:45px}.v4-timeline i{width:8px;height:8px;margin-top:4px;border:2px solid #0b7acb;border-radius:50%;background:#fff}.v4-timeline>div:not(:last-child)::after{content:"";position:absolute;left:4px;top:15px;bottom:-1px;border-left:1px solid #b9c7d6}.v4-timeline span{display:grid}.v4-timeline b{font-size:9.8px}.v4-timeline small{font-size:8.8px;color:#6b7d91}.v4-timeline .muted i{border-color:#94a3b8}
  .v4-slider{display:grid;gap:3px;margin:8px 0}.v4-slider span{display:flex;justify-content:space-between;font-size:9.5px}.v4-slider input{width:100%}.v4-field{display:grid;gap:4px;margin:7px 0}.v4-field>span{font-size:9px;font-weight:750;color:#566a80}.v4-score{display:grid;grid-template-columns:1fr auto;gap:4px 10px;align-items:center;background:#f0f8ff;border-color:#b9d9f0}.v4-score>span{font-size:9.5px}.v4-score>strong{grid-row:1/3;grid-column:2;font-size:34px;color:#0b7acb}.v4-score>b{font-size:11px;color:#153c61}.v4-score>small{grid-column:1/3;color:#64748b;font-size:8.5px}.v4-score>button{grid-column:1/3;margin-top:4px}.v4-grid2{display:grid;grid-template-columns:1fr 1fr;gap:7px}.v4-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.v4-metrics div{display:grid;padding:7px;background:#f5f8fb;border:1px solid #e0e7ef;border-radius:4px;text-align:center}.v4-metrics span{font-size:8px;color:#66788c}.v4-metrics b{font-size:15px;color:#163e66}.v4-title-row{display:flex;align-items:center;justify-content:space-between}.v4-title-row h3{margin:0}.v4-title-row button{padding:5px 7px}.v4-orders{display:grid;gap:4px;margin-top:8px}.v4-orders>div{display:grid;grid-template-columns:1fr auto;gap:6px;padding:6px;border:1px solid #e2e8f0;border-radius:4px}.v4-orders span{display:grid;min-width:0}.v4-orders b{font-size:8.8px}.v4-orders small{overflow:hidden;font-size:8.3px;color:#64748b;text-overflow:ellipsis;white-space:nowrap}.v4-orders em{font-size:8px;color:#0b7acb;font-style:normal}.v4-console footer{display:flex;align-items:center;gap:5px;padding:6px 10px;background:#edf2f7;border-top:1px solid #d8e1eb;color:#607286;font-size:8.5px}
  @media(max-width:900px){.v4-launch{left:12px}.v4-console{top:72px;bottom:92px}.v4-tabs{grid-template-columns:repeat(3,1fr)}}
  `}</style></>;
}
